version: '3'
services:
  frontend:
    build:
      dockerfile: docker/frontend/Dockerfile
      context: ./
    user: ${CURRENT_UID}
    volumes:
      - ./frontend:/opt/frontend
    ports:
      - 4000:4000
